### ISSUE TITLE
LodeSTAR - surface area of identified patterns

### ISSUE THREAD

**Issue by arthurfl** [DeepTrackAI/DeepTrack2#209]
Hi there, 

Although I can easily access positions of identified patterns using LodeSTAR, I have troubles understanding if it's possible to access features associated with these patterns, such as their surface area. Is this possible currently? 

many thanks, 
Arthur

**Comment by BenjaminMidtvedt** [comment]
@arthurfl Hi! Sadly, the current implementation of lodestar only extracts the position of the object. We are working on a updated version that also extracts morphological information
