### ISSUE TITLE
Error in "01. deeptrack_introduction_tutorial.ipynb" from the README tutorials

### ISSUE THREAD

**Issue by james-chow** [DeepTrackAI/DeepTrack2#217]
Hello,
I've run into an error in the first tutorial, in section 2. Retrieve information about the image. Here it is on Colab:

![Screenshot 2024-09-20 191712](https://github.com/user-attachments/assets/9ec8afc7-8065-4515-9789-5bff81ad87e7)

It appears the "experimental_image" call method is producing an np.ndarray rather than an Image object. Running it locally (on python 3.8) produces the same error for me. Please advise.

**Comment by dimitar10** [comment]
@james-chow try and remove the second pair of brackets:

`experimental_image.update()()` -> `experimental_image.update()`
