### ISSUE TITLE
Need Help Urgently: deeptrack.models couldn't be loaded 

### ISSUE THREAD

**Issue by shuyiloe** [DeepTrackAI/DeepTrack2#224]
I open the lodeSTAR example 03.track_BF-C2DL-HSC.ipynb. After running `model = dt.models.LodeSTAR(input_shape=(None, None, 1))`, it reports an ImportError. My pytorch version is 2.5.1 and python version is 3.10. All dependencies are installed and checked according to the reqiurement.txt. 
![屏幕截图 2024-11-28 160726](https://github.com/user-attachments/assets/e514e0d2-6643-49c0-a232-8fe7538b8d8f)
It is weird that when i run the same example code in an tensroflow(2.10) environment, the model can be loaded successfully. However, when i train the model with `model.fit()`, it reports an Attributeerror—— 'numpy.ndarray' object has no attribute 'properties'
![屏幕截图 2024-11-28 161741](https://github.com/user-attachments/assets/0d254ce2-cc67-4bd5-8bdf-3411ebe3a37a)
In the annoncement of the latest release version, it says that pipeline no longer returns Image object, instead it returns ndarray. So i think the problem may be that the model expects the training sample to be image object but recieves ndarray. I don't know how to fix this problem, can anyone help me with that? I would really appreciate any immediate assistance with this issue.

**Comment by BenjaminMidtvedt** [comment]
@shuyiloe hi!

DeepTrack does not support tensorflow>2.10, as these newer versions include a lot of breaking that are not compatible with deeptrack.

The properties issue is separate, and is fixed on the develop branch. You can either downgrade deeptrack to 1.7, or pull the develop branch locally and install it with `pip install -e .`
