### ISSUE TITLE
Identical RNG  when using the ** Feature operator

### ISSUE THREAD

**Issue by b-grimaud** [DeepTrackAI/DeepTrack2#76]
I tried the example code provided in Google Colab, and generating multiple particles with `five_particles = particle^5` worked fine.
However, as I'm trying to generate images with different x and y dimensions, I wrote a function generating a tuple of random numbers, each within the limits of their respective axes. 

```
def rand():
    np.random.seed()
    y = np.random.rand() * y_dim
    x = np.random.rand() * x_dim

   return y,x
```

```
particle = dt.PointParticle(
    position=rand(),
    position_unit="pixel",
    intensity=1

five_particles = particle**5
```

However, doing so will generate five particles as the exact same spot. They obviously appear as a single spot in the image, but using `get_positions(image)` as provided in the example, it shows that there are indeed 5 particles stacked on top of each other.

```
positions = get_positions(output_image)
print(positions)

[[18.94063765 60.07266853]
 [18.94063765 60.07266853]
 [18.94063765 60.07266853]
 [18.94063765 60.07266853]
 [18.94063765 60.07266853]]
```

Calling the function I wrote in a loop generates distinct tuples. At first I believed it could be a numpy issue, and indeed there are some [reports](https://github.com/pytorch/pytorch/issues/5059) of it generating the same number in some cases of subprocessing, but the exact same issue happens when using Python's own random library.

```
def prand():
    random.seed()
    y = random.uniform(0,1) * y_dim
    x = random.uniform(0,1) * x_dim

    return y,x
```

Is there anything specific in the way features are called repeatedly with the `^` operator that could explain such results ?

**Comment by BptGrm** [comment]
Thank you for the answer, it did solve the problem !

I otherwise found a workaround by training a model on square pictures and padding my experimental data with empty arrays, as I know machile learning generally performs better on data with similar dimensions.

Is there a dedicated forum or space to communicate about DeepTrack ? I have questions that aren't strictly about code, and I don't know if GitHub issues are the right space for them.
